# Generated by Django 6.0.8 on 2026-08-17 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("road_id", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("from_point", models.CharField(max_length=100)),
                ("to_point", models.CharField(max_length=100)),
                ("traffic", models.IntegerField()),
                ("speed", models.IntegerField()),
                ("noise", models.IntegerField()),
                ("risk", models.CharField(default="MODERATE", max_length=10)),
                ("coordinates", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("temp", models.FloatField()),
                ("pm25", models.IntegerField()),
                ("aqi", models.CharField(default="Moderate", max_length=20)),
                ("confidence", models.CharField(default="sensor", max_length=20)),
                ("vulnerability", models.IntegerField(default=5)),
                ("tree_cover", models.IntegerField(default=20)),
                ("reason", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SimulationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intervention", models.CharField(max_length=20)),
                ("intensity", models.IntegerField()),
                ("simulated_temp", models.FloatField()),
                ("simulated_pm25", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="twin.zone"
                    ),
                ),
            ],
        ),
    ]
